Avoiding entire renderer instantiation after the resize of the control
varon/GLWpfControl pull request #23
Opened 2020-11-23 09:05 UTC by marcotod1410

This PR aims to avoid the need to the entire disposal of the renderer when the control resizes.

When resizing, the only important thing is to create a new rendertarget, along with the corresponding framebuffers (disposing old ones, of course). In fact, the d3d9 device can still be used again.

As a note, you can see that the BackbufferWidth and BackbufferHeight are set to 1. In fact, in this use case, the backbuffer is not used, as we're relying on the created rendertargets.

2020-11-23 17:46 UTC, varon requested changes
Minor style changes, but overall looks good. A solid contribution.

One thing though is we're now handling a ton of state inside both `GlWpfControl` and `RendererDX`. 

The general design approach we were going for when we started this to keep things simple - just create a new renderer when we changed sizes, etc etc.

If we want to keep the context/ dx device stuff between them and avoid re-creating that, good design here would be to move that into a state object that gets passed into the renderers.

Obviously this is a fairly significant change, so if you're not up for it we can probably just live with what we have now + the requested style changes.

2020-11-23 17:46 UTC, varon commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +            if (_glFrameBuffer != 0)
Style: No short ifs

2020-11-23 17:46 UTC, varon commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +            if(_glSharedTexture != 0)
Same for these too.

2020-11-23 17:46 UTC, varon commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +        public void Resize(int renderWidth, int renderHeight)
Let's name this `SetRenderBufferSize`

2020-11-23 19:38 UTC, Eschryn reviewed
Maybe some suggestions & things to consider

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +        private bool recreatingSurfaceNeeded = true;
```suggestion
```

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +                return;
As i see it - this variable isnt really required at all - the only times where the surface has to be recreated is either when the renderer has been created or the control has been resized - my suggestion: instead of using conditionals, and a variable to track when to recreate the surface - just call this method instead of setting this boolean to true. 
```suggestion
```

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +            recreatingSurfaceNeeded = true;
```suggestion
            EnsureSurfaceCreated();
```

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +        }
```suggestion
            EnsureSurfaceCreated();
        }
```

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +        private void EnsureSurfaceCreated()
Maybe rename this function to `CreateSurface`

2020-11-23 19:38 UTC, Eschryn commented on src/GLWpfControl/GLWpfControlRendererDX.cs
> +            DeleteBuffers();
Why does a function that creates a buffer delete them - move that call to where its needed (which is effectively just when the buffer is recreated)

2020-11-23 23:05 UTC, marcotod1410 commented
Thank you for your reviews.
See also #24 where I addressed the problem of simplifying the state management between the control and the renderer.

2020-11-24 19:19 UTC, varon commented
This is superceded and fixed by #24 !

2020-11-24 19:19 UTC, closed without merging